data:
    dataset: "S-UIEB-tmp"
    category: "type_3"
    image_size: 256
    channels: 3
    num_workers: 32
    data_dir: "/home/bachnguyen/Desktop/SLAM/underwater/UW-DDIM"
    conditional: False

tb_path: "/home/bachnguyen/Desktop/SLAM/underwater/UW-DDIM/logs"

model:
    type: "simple"
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    var_type: fixedsmall
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    batch_size: 1
    n_epochs: 500000
    n_iters: 2000000
    snapshot_freq: 5000
    validation_freq: 2000

sampling:
    batch_size: 32
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    amsgrad: False
    eps: 0.00000001
